# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: SqlAzureDacpacDeployment@1
  displayName: Execute SQL
  inputs:
    azureSubscription : 'AzureConnection'
    ServerName: 'testsqlazuredatabase.database.windows.net'
    DatabaseName: 'testsql_d'
    SqlUsername: 'mwalia'
    SqlPassword: 'Password@1'
    DacpacFile: '$(system.defaultworkingdirectory)/TestAzureSQLDatabase.dacpac'
    
